language: node_js
node_js:
  - "9"

env:
  global:
  - ENCRYPTION_LABEL: "cabb09466128"
  - COMMIT_AUTHOR_EMAIL: "travis@cocomake.co"
  - COMMIT_AUTHOR_NAME: "Travis CI"

before_install:
  - uname -a
  - sudo apt-get -qq update
  - sudo apt-get install zip

script:
  - bash build.sh

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: "dist/*.zip"    
  skip_cleanup: true
  on:
    tags: true
    branch: master