version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            choco install wget
            curl -O https://nuwen.net/files/mingw/mingw-17.1-without-git.exe
            mingw-17.1-without-git.exe -o"C:\MinGW" -y
            set PATH="%PATH%;c:\MinGW\bin"
            make
            

